"""Aggregate ``benchmarks/results/*.csv`` into a chart dashboard + ``docs/report.md``
and inject a results table + chart into the README.

Computes, per (pipeline, arch, emulated), the quantization trade-off relative to
that pipeline's FP32 baseline: size reduction, latency speedup, accuracy delta.
Emulated-ARM rows are kept separate from native rows so the story stays honest.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from .config import results_root
from .utils import get_logger

log = get_logger("report")

_DOCS = Path("docs")
_IMAGES = _DOCS / "images"
_README = Path("README.md")
_README_BEGIN = "<!-- RESULTS_TABLE -->"
_README_END = "<!-- /RESULTS_TABLE -->"
_DASHBOARD = _IMAGES / "results_dashboard.png"

# Friendly, compact axis labels.
_LABELS = {
    "ffn_mnist": "FFN\nMNIST",
    "cnn_cifar10": "CNN\nCIFAR-10",
    "rnn_imdb": "RNN\nIMDB",
    "distilbert_imdb": "DistilBERT\nIMDB",
}
_ORDER = ["ffn_mnist", "cnn_cifar10", "rnn_imdb", "distilbert_imdb"]


def load_results(results_dir: Path | None = None) -> pd.DataFrame:
    results_dir = results_dir or results_root()
    csvs = sorted(p for p in results_dir.glob("*.csv"))
    if not csvs:
        return pd.DataFrame()
    return pd.concat([pd.read_csv(c) for c in csvs], ignore_index=True)


def _baseline_map(df: pd.DataFrame) -> dict[tuple, pd.Series]:
    base = df[df["variant"] == "fp32"]
    return {(r["pipeline"], r["arch"], r["emulated"]): r for _, r in base.iterrows()}


def summarize(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df
    baselines = _baseline_map(df)
    rows = []
    for _, r in df.iterrows():
        b = baselines.get((r["pipeline"], r["arch"], r["emulated"]))
        size_red = lat_speedup = acc_delta = float("nan")
        if b is not None and b["size_mb"]:
            size_red = 100.0 * (b["size_mb"] - r["size_mb"]) / b["size_mb"]
            if r["latency_ms_mean"]:
                lat_speedup = b["latency_ms_mean"] / r["latency_ms_mean"]
            acc_delta = r["accuracy"] - b["accuracy"]
        rows.append(
            {
                "pipeline": r["pipeline"],
                "modality": r["modality"],
                "runtime": r["runtime"],
                "variant": r["variant"],
                "arch": r["arch"],
                "emulated": bool(r["emulated"]),
                "size_mb": round(r["size_mb"], 3),
                "accuracy": round(r["accuracy"], 4),
                "latency_ms_mean": round(r["latency_ms_mean"], 3),
                "size_reduction_%": round(size_red, 1),
                "latency_speedup_x": round(lat_speedup, 2),
                "accuracy_delta": round(acc_delta, 4),
            }
        )
    return pd.DataFrame(rows)


def _markdown_table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "| " + " | ".join("---" for _ in cols) + " |"]
    for _, r in df.iterrows():
        lines.append("| " + " | ".join("" if pd.isna(r[c]) else str(r[c]) for c in cols) + " |")
    return "\n".join(lines)


def _readme_table(summary: pd.DataFrame, arch: str) -> str:
    cols = [
        "pipeline", "modality", "variant", "size_mb", "accuracy",
        "size_reduction_%", "latency_speedup_x", "accuracy_delta",
    ]
    view = summary[(summary["arch"] == arch) & (~summary["emulated"].astype(bool))][cols]
    return _markdown_table(view.reset_index(drop=True))


def inject_readme_table(
    table_md: str, arch: str, chart_rel: str | None = None, readme: Path = _README
) -> bool:
    """Replace the span between the RESULTS_TABLE sentinels with chart + table."""
    if not readme.exists():
        return False
    text = readme.read_text(encoding="utf-8")
    if _README_BEGIN not in text or _README_END not in text:
        return False
    pre, rest = text.split(_README_BEGIN, 1)
    _, post = rest.split(_README_END, 1)
    chart = f"\n![Quantization trade-offs]({chart_rel})\n" if chart_rel else ""
    block = (
        f"{_README_BEGIN}\n\n_Auto-generated by `bsb report` from "
        f"`benchmarks/results/*.csv` (native {arch}). Full write-up: "
        f"[docs/report.md](docs/report.md)._\n{chart}\n{table_md}\n\n{_README_END}"
    )
    readme.write_text(pre + block + post, encoding="utf-8")
    return True


def _paired(df: pd.DataFrame, arch: str) -> pd.DataFrame:
    """One row per pipeline pairing the FP32 baseline with its quantized variant."""
    d = df[df["arch"] == arch]
    present = set(d["pipeline"])
    rows = []
    for p in [x for x in _ORDER if x in present] + [x for x in present if x not in _ORDER]:
        sub = d[d["pipeline"] == p]
        fp = sub[sub["variant"] == "fp32"]
        q = sub[sub["variant"] != "fp32"]
        if fp.empty or q.empty:
            continue
        fp, q = fp.iloc[0], q.iloc[0]
        rows.append(
            {
                "label": _LABELS.get(p, p),
                "fp32_size": fp["size_mb"], "q_size": q["size_mb"],
                "fp32_acc": fp["accuracy"], "q_acc": q["accuracy"],
                "fp32_lat": fp["latency_ms_mean"], "q_lat": q["latency_ms_mean"],
                "reduction": 100.0 * (fp["size_mb"] - q["size_mb"]) / fp["size_mb"]
                if fp["size_mb"] else 0.0,
            }
        )
    return pd.DataFrame(rows)


def _dashboard(paired: pd.DataFrame, arch: str, out: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    if paired.empty:
        raise ValueError("no paired fp32/quantized rows to chart")

    labels = list(paired["label"])
    x = np.arange(len(labels))
    w = 0.38
    fp_color, q_color = "#9aa7b8", "#2e7d32"

    fig, axes = plt.subplots(2, 2, figsize=(11, 8))
    fig.suptitle(f"Quantization trade-offs by pipeline ({arch})", fontsize=14, fontweight="bold")

    def grouped(ax, fp_vals, q_vals, title, ylabel, *, log=False, fmt="%.2f"):
        b1 = ax.bar(x - w / 2, fp_vals, w, label="FP32", color=fp_color)
        b2 = ax.bar(x + w / 2, q_vals, w, label="quantized", color=q_color)
        ax.set_title(title)
        ax.set_ylabel(ylabel)
        ax.set_xticks(x)
        ax.set_xticklabels(labels, fontsize=8)
        if log:
            ax.set_yscale("log")
        ax.bar_label(b1, fmt=fmt, fontsize=7, padding=2)
        ax.bar_label(b2, fmt=fmt, fontsize=7, padding=2)
        ax.legend(fontsize=8)
        ax.grid(axis="y", alpha=0.3)

    grouped(axes[0, 0], paired["fp32_size"], paired["q_size"],
            "Model size", "MB (log scale)", log=True)
    grouped(axes[0, 1], paired["fp32_acc"], paired["q_acc"],
            "Accuracy retention", "accuracy", fmt="%.3f")
    axes[0, 1].set_ylim(0, 1.08)
    grouped(axes[1, 0], paired["fp32_lat"], paired["q_lat"],
            "Inference latency", "ms (log scale)", log=True)

    bars = axes[1, 1].bar(x, paired["reduction"], w * 1.6, color="#1565c0")
    axes[1, 1].set_title("Size reduction")
    axes[1, 1].set_ylabel("% smaller")
    axes[1, 1].set_xticks(x)
    axes[1, 1].set_xticklabels(labels, fontsize=8)
    axes[1, 1].set_ylim(0, 100)
    axes[1, 1].bar_label(bars, fmt="%.0f%%", fontsize=8, padding=2)
    axes[1, 1].grid(axis="y", alpha=0.3)

    fig.tight_layout(rect=(0, 0, 1, 0.96))
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=130)
    plt.close(fig)


def generate_report(results_dir: Path | None = None) -> Path | None:
    df = load_results(results_dir)
    if df.empty:
        log.warning("No results in %s — run `bsb benchmark <pipeline>` first.", results_root())
        return None

    summary = summarize(df)
    native = df[~df["emulated"].astype(bool)]
    headline = native if not native.empty else df
    primary_arch = headline["arch"].mode().iloc[0]

    chart_ok = False
    try:
        _dashboard(_paired(headline, primary_arch), primary_arch, _DASHBOARD)
        chart_ok = True
    except Exception as exc:  # never let a plotting hiccup kill the report
        log.warning("Could not render dashboard: %s", exc)

    report_path = _DOCS / "report.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    parts = [
        "# Byte-Sized Brain — Results\n",
        "_Generated by `bsb report` from `benchmarks/results/*.csv`._\n",
    ]
    if chart_ok:
        parts += [f"## Quantization trade-offs ({primary_arch})\n",
                  f"![Quantization trade-offs]({_DASHBOARD.relative_to(_DOCS).as_posix()})\n"]
    parts += ["## Per-variant detail\n", _markdown_table(summary), "", "## Notes\n",
              "- `size_reduction_%`, `latency_speedup_x` and `accuracy_delta` are computed "
              "against each pipeline's own FP32 baseline, within the same architecture.",
              "- Rows with `emulated = True` come from QEMU-emulated ARM64; their **absolute "
              "latency is not comparable** to native runs — treat it as a relative ratio only. "
              "See `docs/methodology.md`."]
    report_path.write_text("\n".join(parts) + "\n", encoding="utf-8")
    log.info("Wrote %s (dashboard: %s)", report_path, chart_ok)

    chart_rel = _DASHBOARD.as_posix() if chart_ok else None
    if inject_readme_table(_readme_table(summary, primary_arch), primary_arch, chart_rel):
        log.info("Injected results table + chart into %s", _README)

    return report_path
