"""Aggregate ``benchmarks/results/*.csv`` into charts + ``docs/report.md``.

Computes, per (pipeline, arch, emulated), the quantization trade-off relative to
that pipeline's FP32 baseline: size reduction, latency speedup, accuracy delta.
Emulated-ARM rows are kept separate from real rows so the story stays honest.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from .config import results_root
from .utils import get_logger

log = get_logger("report")

_DOCS = Path("docs")
_IMAGES = _DOCS / "images"
_README = Path("README.md")
_README_BEGIN = "<!-- RESULTS_TABLE -->"
_README_END = "<!-- /RESULTS_TABLE -->"


def load_results(results_dir: Path | None = None) -> pd.DataFrame:
    results_dir = results_dir or results_root()
    csvs = sorted(p for p in results_dir.glob("*.csv"))
    if not csvs:
        return pd.DataFrame()
    frames = [pd.read_csv(c) for c in csvs]
    return pd.concat(frames, ignore_index=True)


def _baseline_map(df: pd.DataFrame) -> dict[tuple, pd.Series]:
    """FP32 baseline row keyed by (pipeline, arch, emulated)."""
    base = df[df["variant"] == "fp32"]
    return {
        (r["pipeline"], r["arch"], r["emulated"]): r for _, r in base.iterrows()
    }


def summarize(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df
    baselines = _baseline_map(df)
    rows = []
    for _, r in df.iterrows():
        key = (r["pipeline"], r["arch"], r["emulated"])
        b = baselines.get(key)
        size_red = lat_speedup = acc_delta = float("nan")
        if b is not None and b["size_mb"]:
            size_red = 100.0 * (b["size_mb"] - r["size_mb"]) / b["size_mb"]
            if r["latency_ms_mean"]:
                lat_speedup = b["latency_ms_mean"] / r["latency_ms_mean"]
            acc_delta = r["accuracy"] - b["accuracy"]
        rows.append(
            {
                "pipeline": r["pipeline"],
                "modality": r["modality"],
                "runtime": r["runtime"],
                "variant": r["variant"],
                "arch": r["arch"],
                "emulated": bool(r["emulated"]),
                "size_mb": round(r["size_mb"], 3),
                "accuracy": round(r["accuracy"], 4),
                "latency_ms_mean": round(r["latency_ms_mean"], 3),
                "size_reduction_%": round(size_red, 1),
                "latency_speedup_x": round(lat_speedup, 2),
                "accuracy_delta": round(acc_delta, 4),
            }
        )
    return pd.DataFrame(rows)


def _markdown_table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    head = "| " + " | ".join(cols) + " |"
    sep = "| " + " | ".join("---" for _ in cols) + " |"
    lines = [head, sep]
    for _, r in df.iterrows():
        lines.append("| " + " | ".join("" if pd.isna(r[c]) else str(r[c]) for c in cols) + " |")
    return "\n".join(lines)


def _readme_table(summary: pd.DataFrame, arch: str) -> str:
    """A compact per-pipeline table for the README (one architecture, native)."""
    cols = [
        "pipeline", "modality", "variant", "size_mb", "accuracy",
        "size_reduction_%", "latency_speedup_x", "accuracy_delta",
    ]
    view = summary[(summary["arch"] == arch) & (~summary["emulated"].astype(bool))][cols]
    return _markdown_table(view.reset_index(drop=True))


def inject_readme_table(table_md: str, arch: str, readme: Path = _README) -> bool:
    """Replace the span between the RESULTS_TABLE sentinels in README.md."""
    if not readme.exists():
        return False
    text = readme.read_text(encoding="utf-8")
    if _README_BEGIN not in text or _README_END not in text:
        return False
    pre, rest = text.split(_README_BEGIN, 1)
    _, post = rest.split(_README_END, 1)
    block = (
        f"{_README_BEGIN}\n\n_Auto-generated by `bsb report` from "
        f"`benchmarks/results/*.csv` (native {arch}). Full table + charts: "
        f"[docs/report.md](docs/report.md)._\n\n{table_md}\n\n{_README_END}"
    )
    readme.write_text(pre + block + post, encoding="utf-8")
    return True


def _bar_chart(df: pd.DataFrame, value: str, title: str, ylabel: str, out: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    pivot = df.pivot_table(index="pipeline", columns="variant", values=value, aggfunc="mean")
    ax = pivot.plot(kind="bar", figsize=(8, 4.5), rot=20)
    ax.set_title(title)
    ax.set_ylabel(ylabel)
    ax.set_xlabel("")
    ax.legend(title="variant")
    ax.figure.tight_layout()
    out.parent.mkdir(parents=True, exist_ok=True)
    ax.figure.savefig(out, dpi=120)
    plt.close(ax.figure)


def generate_report(results_dir: Path | None = None) -> Path | None:
    df = load_results(results_dir)
    if df.empty:
        log.warning("No results found in %s — run `bsb benchmark <pipeline>` first.", results_root())
        return None

    summary = summarize(df)
    # Headline charts use the primary (most common) non-emulated arch for clarity.
    headline = df[~df["emulated"].astype(bool)]
    if headline.empty:
        headline = df
    primary_arch = headline["arch"].mode().iloc[0]
    chart_df = headline[headline["arch"] == primary_arch]

    _IMAGES.mkdir(parents=True, exist_ok=True)
    charts = {
        "size_mb": ("Model size by variant", "Size (MB)", _IMAGES / "size_by_variant.png"),
        "accuracy": ("Accuracy by variant", "Accuracy", _IMAGES / "accuracy_by_variant.png"),
        "latency_ms_mean": ("Mean latency by variant", "Latency (ms)", _IMAGES / "latency_by_variant.png"),
    }
    made = []
    for value, (title, ylabel, out) in charts.items():
        try:
            _bar_chart(chart_df, value, f"{title} ({primary_arch})", ylabel, out)
            made.append(out)
        except Exception as exc:  # never let a plotting hiccup kill the report
            log.warning("Could not render %s chart: %s", value, exc)

    report_path = _DOCS / "report.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    parts = [
        "# Byte-Sized Brain — Results\n",
        "_Generated by `bsb report` from `benchmarks/results/*.csv`._\n",
        "## Quantization trade-offs\n",
        _markdown_table(summary),
        "",
        f"## Charts ({primary_arch})\n",
    ]
    for out in made:
        rel = out.relative_to(_DOCS).as_posix()
        parts.append(f"![{out.stem}]({rel})\n")
    parts += [
        "## Notes\n",
        "- `size_reduction_%`, `latency_speedup_x` and `accuracy_delta` are computed "
        "against each pipeline's own FP32 baseline, within the same architecture.",
        "- Rows with `emulated = True` come from QEMU-emulated ARM64; their **absolute "
        "latency is not comparable** to native runs — treat emulated latency as a relative "
        "ratio only. See `docs/methodology.md`.",
    ]
    report_path.write_text("\n".join(parts) + "\n", encoding="utf-8")
    log.info("Wrote %s and %d chart(s) to %s", report_path, len(made), _IMAGES)

    if inject_readme_table(_readme_table(summary, primary_arch), primary_arch):
        log.info("Injected results table into %s", _README)

    return report_path
